"""HuggingFace Integration — push datasets to HF Hub with versioning."""

from __future__ import annotations

import datetime
import json
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


class HuggingFacePusher:
    """Push generated datasets to HuggingFace Hub."""

    def __init__(self, token: Optional[str] = None):
        self.token = token
        self._client = None

    def _get_client(self):
        if self._client is None:
            from huggingface_hub import HfApi
            self._client = HfApi(token=self.token)
        return self._client

    def push(
        self,
        repo_id: str,
        dataset: dict,
        filename: str = "dataset.json",
        private: bool = False,
        commit_message: str = "Update dataset",
        version: Optional[str] = None,
    ) -> str:
        """Push a dataset to HuggingFace Hub.
        
        Args:
            repo_id: Repository ID (e.g. "username/my-dataset")
            dataset: Dataset dict with items
            filename: Name of the output file
            private: Whether the repo should be private
            commit_message: Commit message
            version: Version tag (e.g. "v1.0", "v1.1")
        
        Returns:
            URL to the pushed dataset
        """
        from huggingface_hub import create_repo, upload_file
        import tempfile

        api = self._get_client()

        # Create repo if it doesn't exist
        try:
            create_repo(
                repo_id=repo_id,
                repo_type="dataset",
                private=private,
                token=self.token,
                exist_ok=True,
            )
        except Exception as exc:
            logger.warning(f"Repo may already exist: {exc}")

        # Write dataset to temp file
        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8") as f:
            json.dump(dataset, f, ensure_ascii=False, indent=2)
            temp_path = f.name

        try:
            upload_file(
                path_or_fileobj=temp_path,
                path_in_repo=filename,
                repo_id=repo_id,
                repo_type="dataset",
                commit_message=commit_message,
                token=self.token,
            )
        finally:
            import os
            os.unlink(temp_path)

        # Create version tag if specified
        if version:
            try:
                from huggingface_hub import create_tag
                create_tag(
                    repo_id=repo_id,
                    repo_type="dataset",
                    tag=version,
                    token=self.token,
                )
            except Exception:
                pass  # Tag may already exist

        url = f"https://huggingface.co/datasets/{repo_id}"
        return url

    def generate_dataset_card(
        self,
        project_name: str,
        description: str,
        schema: dict,
        stats: dict,
        platform: str,
        config_file: Optional[str] = None,
    ) -> str:
        """Generate a HuggingFace dataset card (README.md)."""
        now = datetime.datetime.utcnow().isoformat() + "Z"
        card = f"""---
license: mit
language:
- en
task_categories:
- text-generation
- question-answering
platforms:
- {platform}
---

# {project_name}

## Dataset Description

{description}

**Generated**: {now}
**Platform**: {platform}
**Total items**: {stats.get('total_items', 'N/A')}

## Schema

This dataset follows the schema defined in the aigen-cli configuration.

"""
        if schema.get("fields"):
            card += "### Fields\n\n"
            for field in schema["fields"]:
                req = " (required)" if field in schema.get("required", []) else ""
                card += f"- **{field}**{req}\n"
            card += "\n"

        if stats:
            card += "## Generation Statistics\n\n"
            for key, val in stats.items():
                card += f"- **{key}**: {val}\n"
            card += "\n"

        card += """## Generation Method

This dataset was generated using [aigen-cli](https://github.com/aigen-cli/aigen-cli),
a zero-API, browser-based AI generation toolkit. Items were generated by prompting
web AI platforms and parsing their responses into structured JSON.

## Usage

```python
from datasets import load_dataset

ds = load_dataset("REPO_ID")
print(ds["train"][0])
```

## Citation

```
@misc{aigen-cli,
  title={aigen-cli: Zero-API AI Dataset Generation},
  year={2026},
  url={https://github.com/aigen-cli/aigen-cli}
}
```
"""
        return card


class DatasetVersioner:
    """Track dataset versions with diffs between runs."""

    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.versions_dir = output_dir / "versions"
        self.versions_dir.mkdir(parents=True, exist_ok=True)

    def create_version(self, version: str, items: list[dict], prev_version: Optional[str] = None) -> dict:
        """Create a dataset version and compute diff from previous."""
        version_path = self.versions_dir / f"{version}.json"

        # Save current version
        with open(version_path, "w", encoding="utf-8") as f:
            json.dump(items, f, ensure_ascii=False, indent=2)

        # Compute diff
        diff = {"version": version, "total": len(items)}

        if prev_version:
            prev_path = self.versions_dir / f"{prev_version}.json"
            if prev_path.exists():
                prev_items = json.loads(prev_path.read_text(encoding="utf-8"))
                prev_ids = {item.get("id", item.get("fingerprint", str(i))) for i, item in enumerate(prev_items)}
                curr_ids = {item.get("id", item.get("fingerprint", str(i))) for i, item in enumerate(items)}

                diff["added"] = len(curr_ids - prev_ids)
                diff["removed"] = len(prev_ids - curr_ids)
                diff["total_prev"] = len(prev_items)
                diff["total_curr"] = len(items)
        else:
            diff["added"] = len(items)
            diff["removed"] = 0
            diff["total_prev"] = 0
            diff["total_curr"] = len(items)

        # Save diff
        diff_path = self.versions_dir / f"{version}_diff.json"
        diff_path.write_text(json.dumps(diff, indent=2), encoding="utf-8")

        return diff

    def list_versions(self) -> list[str]:
        """List all dataset versions."""
        versions = []
        for f in sorted(self.versions_dir.glob("*.json")):
            if "_diff" not in f.name:
                versions.append(f.stem)
        return versions
